#!/usr/bin/env python3
"""Visual witness for local-minimum trapping in the revived annealer.

The script runs the same causal set and the same Bombelli energy under two
annealing schedules. It writes an SVG where each thin line is one random seed:

* red/orange: Bombelli-default schedule, typically freezing at positive energy;
* green/blue: hotter tuned schedule, typically reaching zero energy.

This is intentionally a visual diagnostic, not a new experiment table. The
numerical schedule comparison used in the paper is generated by experiments.py.
"""

from __future__ import annotations

import argparse
import contextlib
import csv
import html
import io
import math
import os
import platform
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from typing import List, Sequence, Tuple

import cones


ROOT = Path(__file__).resolve().parent
DEFAULT_INPUT = ROOT / "inputs" / "tesis_like_12.in"
ZERO_EPS = 1e-6


@dataclass(frozen=True)
class Schedule:
    label: str
    initial_temp: float
    cooling_factor: float
    stroke: str
    dot: str


@dataclass
class RunTrace:
    schedule: Schedule
    seed: int
    points: List[Tuple[int, float, float]]
    final_energy: float

    @property
    def escaped(self) -> bool:
        return self.final_energy < ZERO_EPS


SCHEDULES = (
    Schedule("L. Bombelli & D. Meyer defaults: T0=100, alpha=0.9", 100.0, 0.9, "#ff5f1f", "#ff2d55"),
    Schedule("Hotter tuned: T0=180, alpha=0.8", 180.0, 0.8, "#00f5d4", "#00ff88"),
)


def run_trace(
    z: Sequence[Sequence[bool]],
    *,
    dim: int,
    seed: int,
    schedule: Schedule,
    max_data: int,
    anneal_limit: int,
    warmup_limit: int,
) -> RunTrace:
    """Run one anneal and keep the per-temperature average-energy trace."""

    with tempfile.TemporaryDirectory() as tmp, contextlib.redirect_stdout(io.StringIO()):
        sim = cones.ConesSimulator(
            z=[list(row) for row in z],
            dim=dim,
            seed=seed,
            interactive=False,
            max_data=max_data,
            plot_path=None,
            warmup_limit=warmup_limit,
            anneal_limit=anneal_limit,
            initial_temp=schedule.initial_temp,
            cooling_factor=schedule.cooling_factor,
        )
        sim.run(Path(tmp) / "cone.out")

    points = [(idx, temp, eave) for idx, (temp, eave) in enumerate(sim.data, start=1)]
    return RunTrace(schedule=schedule, seed=seed, points=points, final_energy=sim.energies[0])


def scale_linear(value: float, lo: float, hi: float, start: float, end: float) -> float:
    if hi == lo:
        return (start + end) / 2.0
    return start + (value - lo) * (end - start) / (hi - lo)


def scale_log_energy(value: float, lo: float, hi: float, top: float, bottom: float) -> float:
    eps = 1e-3
    v = math.log10(max(value, 0.0) + eps)
    vlo = math.log10(max(lo, 0.0) + eps)
    vhi = math.log10(max(hi, 0.0) + eps)
    if vhi == vlo:
        return (top + bottom) / 2.0
    return bottom - (v - vlo) * (bottom - top) / (vhi - vlo)


def polyline_for_trace(
    trace: RunTrace,
    *,
    x0: float,
    x1: float,
    y0: float,
    y1: float,
    max_block: int,
    max_energy: float,
) -> str:
    coords = []
    for block, _temp, eave in trace.points:
        x = scale_linear(block, 1, max_block, x0, x1)
        y = scale_log_energy(eave, 0.0, max_energy, y0, y1)
        coords.append(f"{x:.1f},{y:.1f}")
    return " ".join(coords)


def write_csv(traces: Sequence[RunTrace], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["schedule", "seed", "block", "temperature", "eave", "final_energy", "escaped"])
        for trace in traces:
            for block, temp, eave in trace.points:
                writer.writerow([
                    trace.schedule.label,
                    trace.seed,
                    block,
                    f"{temp:.12g}",
                    f"{eave:.12g}",
                    f"{trace.final_energy:.12g}",
                    int(trace.escaped),
                ])


def write_svg(traces: Sequence[RunTrace], path: Path, *, elapsed_seconds: float) -> None:
    width = 1180
    height = 850
    left = 95
    right = 1045
    top = 95
    bottom = 540
    max_block = max((len(t.points) for t in traces), default=1)
    max_energy = max((e for t in traces for *_rest, e in t.points), default=1.0)
    max_final = max((t.final_energy for t in traces), default=1.0)
    max_energy = max(max_energy, max_final, 1.0)

    grouped = []
    for schedule in SCHEDULES:
        subset = [t for t in traces if t.schedule == schedule]
        successes = sum(1 for t in subset if t.escaped)
        mean_final = sum(t.final_energy for t in subset) / len(subset) if subset else float("nan")
        grouped.append((schedule, subset, successes, mean_final))

    grid_lines = []
    for energy in (0.001, 0.01, 0.1, 1, 10, 100, 1000):
        if energy > max_energy:
            continue
        y = scale_log_energy(energy, 0.0, max_energy, top, bottom)
        grid_lines.append(
            f"<line x1='{left}' y1='{y:.1f}' x2='{right}' y2='{y:.1f}' stroke='#26345f'/>"
            f"<text x='{left - 12}' y='{y + 4:.1f}' text-anchor='end' font-size='12' "
            f"font-family='monospace' fill='#b9c6ff'>{energy:g}</text>"
        )

    x_ticks = []
    for block in range(1, max_block + 1):
        if block == 1 or block == max_block or block % 5 == 0:
            x = scale_linear(block, 1, max_block, left, right)
            x_ticks.append(
                f"<line x1='{x:.1f}' y1='{bottom}' x2='{x:.1f}' y2='{bottom + 6}' stroke='#b9c6ff'/>"
                f"<text x='{x:.1f}' y='{bottom + 22}' text-anchor='middle' font-size='12' "
                f"font-family='monospace' fill='#b9c6ff'>{block}</text>"
            )

    curves = []
    finals = []
    jitter_step = 4.0
    for schedule, subset, _successes, _mean_final in grouped:
        for idx, trace in enumerate(subset):
            points = polyline_for_trace(
                trace,
                x0=left,
                x1=right,
                y0=top,
                y1=bottom,
                max_block=max_block,
                max_energy=max_energy,
            )
            opacity = "0.24" if trace.escaped else "0.42"
            curves.append(
                f"<polyline points='{points}' fill='none' stroke='{schedule.stroke}' "
                f"stroke-width='1.5' opacity='{opacity}'/>"
            )
            x = right + 18 + (idx % 5) * jitter_step
            y = scale_log_energy(trace.final_energy, 0.0, max_energy, top, bottom)
            radius = "4.6" if not trace.escaped else "3.4"
            finals.append(
                f"<circle cx='{x:.1f}' cy='{y:.1f}' r='{radius}' fill='{schedule.dot}' "
                f"opacity='0.86'><title>{html.escape(schedule.label)} seed {trace.seed}: "
                f"final E={trace.final_energy:.6g}</title></circle>"
            )

    legend_rows = []
    y_leg = 608
    for idx, (schedule, subset, successes, mean_final) in enumerate(grouped):
        y = y_leg + idx * 32
        failures = len(subset) - successes
        legend_rows.append(
            f"<line x1='95' y1='{y}' x2='140' y2='{y}' stroke='{schedule.stroke}' "
            f"stroke-width='4' opacity='0.75'/>"
            f"<text x='155' y='{y + 5}' font-family='sans-serif' font-size='17' fill='#f8fafc'>"
            f"{html.escape(schedule.label)}: escaped {successes}/{len(subset)}, "
            f"trapped {failures}/{len(subset)}, mean final E={mean_final:.3g}</text>"
        )

    total_runs = len(traces)
    runs_per_second = total_runs / elapsed_seconds if elapsed_seconds > 0.0 else float("nan")
    cpu_label = platform.processor() or platform.machine()
    if len(cpu_label) > 44:
        cpu_label = cpu_label[:41] + "..."
    host_label = f"{platform.system()} {platform.release()}, {os.cpu_count() or '?'} logical CPUs"
    resource_note = (
        "Interpretation: a 1987 single-run workflow could hide schedule sensitivity; "
        "modern hardware makes ensembles cheap."
    )
    tiny_bar = 12
    huge_bar = 735

    svg = f"""<svg xmlns='http://www.w3.org/2000/svg' width='{width}' height='{height}' viewBox='0 0 {width} {height}'>
  <defs>
    <linearGradient id='bg' x1='0' y1='0' x2='1' y2='1'>
      <stop offset='0%' stop-color='#070816'/>
      <stop offset='58%' stop-color='#10163d'/>
      <stop offset='100%' stop-color='#220b3a'/>
    </linearGradient>
    <filter id='glow' x='-30%' y='-30%' width='160%' height='160%'>
      <feGaussianBlur stdDeviation='2.2' result='blur'/>
      <feMerge>
        <feMergeNode in='blur'/>
        <feMergeNode in='SourceGraphic'/>
      </feMerge>
    </filter>
  </defs>
  <rect width='100%' height='100%' fill='url(#bg)'/>
  <path d='M70 560 H1110 M120 95 V760 M260 95 V760 M400 95 V760 M540 95 V760 M680 95 V760 M820 95 V760 M960 95 V760' stroke='#1d2b5c' stroke-width='1' opacity='0.55'/>
  <text x='95' y='42' font-family='sans-serif' font-size='28' font-weight='700' fill='#f8fafc' filter='url(#glow)'>Local-minimum trapping in the L. Bombelli &amp; D. Meyer annealer</text>
  <text x='95' y='68' font-family='sans-serif' font-size='15' fill='#c4d0ff'>Each line is one seed on inputs/tesis_like_12.in, dim=3.</text>
  <text x='95' y='88' font-family='sans-serif' font-size='15' fill='#c4d0ff'>Positive final energy means the optimizer froze in a nonzero basin; zero energy means a faithful embedding was found.</text>

  <rect x='{left}' y='{top}' width='{right - left}' height='{bottom - top}' fill='#080b1f' stroke='#00f5d4' stroke-opacity='0.7'/>
  {''.join(grid_lines)}
  {''.join(x_ticks)}
  <line x1='{left}' y1='{bottom}' x2='{right}' y2='{bottom}' stroke='#00f5d4' stroke-width='1.6'/>
  <line x1='{left}' y1='{top}' x2='{left}' y2='{bottom}' stroke='#00f5d4' stroke-width='1.6'/>

  {''.join(curves)}
  <line x1='{right}' y1='{top}' x2='{right}' y2='{bottom}' stroke='#f8fafc' stroke-width='1' stroke-dasharray='4 4'/>
  {''.join(finals)}

  <text x='{(left + right) / 2:.1f}' y='{bottom + 36}' text-anchor='middle' font-family='sans-serif' font-size='16' fill='#e0e7ff'>annealing block</text>
  <text x='28' y='{(top + bottom) / 2:.1f}' text-anchor='middle' font-family='sans-serif' font-size='16' fill='#e0e7ff' transform='rotate(-90 28 {(top + bottom) / 2:.1f})'>average energy, log scale</text>
  <text x='{right + 12}' y='{top - 12}' font-family='sans-serif' font-size='13' fill='#e0e7ff'>final energies</text>
  <text x='{right + 12}' y='{bottom + 22}' font-family='sans-serif' font-size='13' fill='#e0e7ff'>zero line</text>

  <line x1='{left}' y1='{scale_log_energy(0.0, 0.0, max_energy, top, bottom):.1f}' x2='{right + 62}' y2='{scale_log_energy(0.0, 0.0, max_energy, top, bottom):.1f}' stroke='#16a34a' stroke-width='1.2' stroke-dasharray='3 3'/>
  {''.join(legend_rows)}

  <rect x='95' y='672' width='950' height='122' rx='6' fill='#0b1026' stroke='#ff2dff' stroke-opacity='0.85'/>
  <text x='115' y='698' font-family='sans-serif' font-size='15' font-weight='700' fill='#ffffff'>Resource context: this is about computational budget, not lack of insight</text>
  <text x='115' y='720' font-family='sans-serif' font-size='13' fill='#c4d0ff'>2026 run here: {total_runs} anneals in {elapsed_seconds:.1f} s ({runs_per_second:.2f}/s) on {html.escape(host_label)}.</text>
  <text x='115' y='739' font-family='sans-serif' font-size='13' fill='#c4d0ff'>CPU label: {html.escape(cpu_label)}. 1987-era context: one workstation and a few costly runs, not cheap seed ensembles.</text>

  <text x='115' y='762' font-family='sans-serif' font-size='12' fill='#f8fafc'>Compute budget</text>
  <text x='230' y='762' font-family='sans-serif' font-size='12' fill='#c4d0ff'>1987</text>
  <rect x='270' y='752' width='{tiny_bar}' height='10' fill='#ff5f1f'/>
  <text x='292' y='762' font-family='sans-serif' font-size='12' fill='#c4d0ff'>one workstation</text>
  <text x='430' y='762' font-family='sans-serif' font-size='12' fill='#c4d0ff'>2026</text>
  <rect x='470' y='752' width='{huge_bar}' height='10' fill='#00f5d4'/>
  <text x='1004' y='762' text-anchor='end' font-family='sans-serif' font-size='12' fill='#07111f' font-weight='700'>cheap ensembles</text>

  <text x='115' y='783' font-family='sans-serif' font-size='12' fill='#f8fafc'>Music budget</text>
  <text x='230' y='783' font-family='sans-serif' font-size='12' fill='#c4d0ff'>1987</text>
  <rect x='270' y='773' width='{huge_bar}' height='10' fill='#ff2dff'/>
  <text x='360' y='783' font-family='sans-serif' font-size='12' fill='#fff7ff'>"Walk Like an Egyptian" (The Bangles)</text>
  <text x='1030' y='783' font-family='sans-serif' font-size='12' fill='#c4d0ff'>2026</text>
  <rect x='1070' y='773' width='{tiny_bar}' height='10' fill='#64748b'/>
  <text x='1090' y='783' font-family='sans-serif' font-size='12' fill='#c4d0ff'>Reggaeton</text>

  <text x='95' y='812' font-family='sans-serif' font-size='13' fill='#aebcff'>{html.escape(resource_note)}</text>
  <text x='95' y='830' font-family='sans-serif' font-size='13' fill='#aebcff'>Generated by visualize_local_minima.py. The y-axis uses log10(E + 1e-3) so exact-zero runs are visible at the bottom.</text>
</svg>
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(svg, encoding="utf-8")


def build_argparser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Draw a local-minimum witness SVG for the Bombelli annealer.")
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT, help="Pascal-style causal-set input")
    parser.add_argument("--dim", type=int, default=3, help="target spatial dimension")
    parser.add_argument("--seeds", type=int, default=32, help="number of consecutive seeds per schedule")
    parser.add_argument("--base-seed", type=int, default=1959, help="first seed")
    parser.add_argument("--max-data", type=int, default=35, help="maximum annealing blocks")
    parser.add_argument("--warmup-limit", type=int, default=100, help="warmup reconfiguration steps")
    parser.add_argument("--anneal-limit", type=int, default=100, help="reconfiguration steps per annealing block")
    parser.add_argument("--output", type=Path, default=Path("local_minima_witness.svg"), help="output SVG path")
    parser.add_argument("--csv", type=Path, default=Path("local_minima_witness.csv"), help="output CSV path")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_argparser().parse_args(argv)
    z = cones.parse_cones_input(args.input)
    seeds = [args.base_seed + i for i in range(args.seeds)]

    started = time.perf_counter()
    traces: List[RunTrace] = []
    for schedule in SCHEDULES:
        for seed in seeds:
            traces.append(
                run_trace(
                    z,
                    dim=args.dim,
                    seed=seed,
                    schedule=schedule,
                    max_data=args.max_data,
                    anneal_limit=args.anneal_limit,
                    warmup_limit=args.warmup_limit,
                )
            )
    elapsed_seconds = time.perf_counter() - started

    write_csv(traces, args.csv)
    write_svg(traces, args.output, elapsed_seconds=elapsed_seconds)

    for schedule in SCHEDULES:
        subset = [t for t in traces if t.schedule == schedule]
        successes = sum(1 for t in subset if t.escaped)
        mean_final = sum(t.final_energy for t in subset) / len(subset)
        print(
            f"{schedule.label}: escaped {successes}/{len(subset)}, "
            f"trapped {len(subset) - successes}/{len(subset)}, "
            f"mean final E={mean_final:.6g}"
        )
    print(f"wrote {args.output}")
    print(f"wrote {args.csv}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
